### ISSUE TITLE
debian package

### ISSUE THREAD

**Issue by alexmyczko** [istoph/editor#26]
would you mind me adding myself to chr debian package and do a team upload, moving salsa repo to debian from chr and fixing https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1071085 ?

alternatively you do it and i just upload it?

for more people be able to install chr binaries and use it: https://buildd.debian.org/status/package.php?p=chr&suite=sid

actually it's ready at http://bananas.ethz.ch/debian/chr/
you'd need to add me to members on salsa so i could move it.

**Comment by istoph** [comment]
@alexmyczko We have added you to the salsa repo. And changed the Vcs-Git and Vcs-Browser already. Please move the repo to the debian group. 

We would be happy if you would like to continue sponsoring the package. Do you want to upload directly from salsa or do you prefer a signed upload to 
mentors? On salsa the new version is ready to upload.

We waited for this release because there were still rebuild problems with cmake dependencies. The same in ubuntu.

**Comment by istoph** [comment]
@alexmyczko sorry, we only saw too late that you had already done so much work with the packaging. We have taken over the relevant parts. Now we are finished. 

Thank you for your efforts.
